version: '2'
services:
    web:
        build: ./
        env_file:
            - ./.env
        ports:
            - 8080:80
        environment:
            - APP_KEY=base64:sRXaSRjIbvM9RojRGopkmMrieswdGApiZZ8sJQdvqR0=